wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.5
    cli_version: 0.17.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1718285321
    t:
      1:
      - 55
      - 95
      - 105
      2:
      - 55
      - 95
      - 105
      3:
      - 2
      - 23
      4: 3.10.5
      5: 0.17.1
      8:
      - 1
      - 5
      13: darwin-x86_64
